"""initial schema

Revision ID: 5ac516642626
Revises: 
Create Date: 2026-06-11 03:35:46.379954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5ac516642626'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('args_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('service_area', sa.Text(), nullable=True),
    sa.Column('premise', sa.Text(), nullable=True),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('staged', 'researching', 'researched', 'disqualified', name='enrichment_status'), server_default=sa.text("'staged'"), nullable=False),
    sa.Column('dq_code', sa.Enum('no_contact_info', 'defunct', 'bad_fit', 'duplicate', 'do_not_contact', 'other', name='dq_reason_code'), nullable=True),
    sa.Column('dq_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('slot_price_cents', sa.Integer(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'filling', 'full', 'fulfillment', 'completed', 'archived', name='campaign_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('email', 'postcard_slot', 'business', name='comment_entity'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('default_slot_price_cents', sa.Integer(), server_default=sa.text('29900'), nullable=False),
    sa.Column('default_total_slots', sa.Integer(), server_default=sa.text('8'), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed_market', sa.Text(), server_default=sa.text("'Lafayette, IN'"), nullable=False),
    sa.Column('operator_business', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outreach_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id', name='settings_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_source', sa.Text(), nullable=True),
    sa.Column('email_confidence', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='contact_reachable'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_primary_contact', 'contacts', ['business_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('prospecting', 'contacted', 'interested', 'waitlisted', 'committed', 'paid', 'declined', name='outreach_status'), server_default=sa.text("'prospecting'"), nullable=False),
    sa.Column('asking_price_cents', sa.Integer(), nullable=False),
    sa.Column('committed_amount_cents', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waitlist_order', sa.Integer(), nullable=True),
    sa.Column('fulfillment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'business_id', name='one_participation_per_business')
    )
    op.create_index('one_committed_per_category', 'participations', ['campaign_id', 'category'], unique=True, postgresql_where=sa.text("status IN ('committed','paid')"))
    op.create_index('waitlist_position', 'participations', ['campaign_id', 'category', 'waitlist_order'], unique=True, postgresql_where=sa.text("status = 'waitlisted'"))
    op.create_table('postcard_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Text(), server_default=sa.text("'grid-4x2-v1'"), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'version', name='one_postcard_version_per_campaign')
    )
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author', sa.Enum('agent', 'operator', name='email_author'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('in_review', 'approved', 'sent', 'superseded', name='email_status'), server_default=sa.text("'in_review'"), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participation_id'], ['participations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participation_id', 'version', name='one_version_per_participation')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['participation_id'], ['participations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactions')
    op.drop_table('emails')
    op.drop_table('postcard_drafts')
    op.drop_index('waitlist_position', table_name='participations', postgresql_where=sa.text("status = 'waitlisted'"))
    op.drop_index('one_committed_per_category', table_name='participations', postgresql_where=sa.text("status IN ('committed','paid')"))
    op.drop_table('participations')
    op.drop_index('one_primary_contact', table_name='contacts', postgresql_where=sa.text('is_primary'))
    op.drop_table('contacts')
    op.drop_table('settings')
    op.drop_table('comments')
    op.drop_table('campaigns')
    op.drop_table('businesses')
    op.drop_table('agent_activity')
    # ### end Alembic commands ###
