"""settings outreach_tone

Revision ID: a023241cbaab
Revises: 5ac516642626
Create Date: 2026-06-11 04:41:12.912945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a023241cbaab'
down_revision: Union[str, None] = '5ac516642626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('outreach_tone', sa.Text(), server_default=sa.text("'neighborly'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'outreach_tone')
    # ### end Alembic commands ###
